version: "3.4"

services:
    database:
        image: "postgres:12"
        ports:
          - "${SQL_PORT}:${SQL_PORT}"
        environment:
          - POSTGRES_USER=${SQL_USER}
          - POSTGRES_PASSWORD=${SQL_PASSWORD}
          - POSTGRES_DATABASE=${SQL_DATABASE}
        volumes:
          - './docker/psql/data:/var/lib/postgresql/data:rw'

    api:
      build:
        dockerfile: Dockerfile
        context: "."
      env_file:
        - .env
      ports:
        - "${API_PORT}:${API_PORT}"
      volumes:
        - ./src:/to-do
      depends_on:
        - database